KEEPALIVED_COMMAND_LINE_ARGUMENTS: --log-detail --dump-conf

# set the interface here to disable the default interface auto detection
# KEEPALIVED_INTERFACE: eth0

KEEPALIVED_PASSWORD: d0cker

# For electing MASTER, highest priority wins.
# to be MASTER, make 50 more than other machines
KEEPALIVED_PRIORITY: 150

KEEPALIVED_UNICAST_PEERS:
  - 192.168.1.10
  - 192.168.1.11

KEEPALIVED_VIRTUAL_IPS:
  - 192.168.1.231
  - 192.168.1.232

KEEPALIVED_NOTIFY: /container/service/keepalived/assets/notify.sh

KEEPALIVED_ROUTER_ID: 51

KEEPALIVED_STATE: BACKUP
