# https://github.com/compose-spec/compose-spec
# https://man7.org/linux/man-pages/man7/capabilities.7.html

version: '3.3'
services:
    keepalived:
        build: https://github.com/nser77/docker-keepalived.git#dev:build
        network_mode: host
        volumes:
            -  /etc/keepalived:/etc/keepalived
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN
            - NET_BROADCAST
            - NET_RAW
        args:
            - __ENABLE_MAGIC__=1
            - __ENABLE_DBUS__=0
            - __DISABLE_IPSET__=0
            - __DISABLE_IPTABLES__=0
            - __DISABLE_NFTABLES__=0
            - __ENABLE_SNMP_VRRP__=0
            - __ENABLE_REGEX__=0
            - __ENABLE_JSON__=0
            - __DISABLE_LVS__=0
            - __DISABLE_VRRP__=0
